CreateResultFile()
Call fundMaster_login()
Call gotoSchemePage()
strSchemeName =  CreateNewScheme()
Call gotoApproveScheme()
Call searchScheme()
Call doCheckListVerification()
Call certifyScheme()
Call approveScheme()
Call cloneAndVerify()
Call gotoMainMenu()
Call gotoAdministrativeExistingUser()
Call verifyUserDetails("Johnte")
Call assignSchemeToUser(strSchemeName)
Call switchToScheme(strSchemeName)
Call verifySchemeNameChanged(strSchemeName)
 
